#!/bin/bash

# This script helps set up MongoDB Atlas connection for Vercel deployment

echo "=========================================="
echo "MongoDB Atlas Setup for Pustakkhana"
echo "=========================================="
echo ""
echo "Follow these steps:"
echo ""
echo "1. Go to: https://www.mongodb.com/cloud/atlas"
echo "2. Create a free account"
echo "3. Create a new project named 'Pustakkhana'"
echo "4. Create a free M0 cluster"
echo "5. Create a database user 'pustakkhana' with a strong password"
echo "6. Get your connection string (replace <password> with your actual password)"
echo ""
echo "Example connection string:"
echo "mongodb+srv://pustakkhana:PASSWORD@cluster0.xxxxx.mongodb.net/pustakkhana?retryWrites=true&w=majority"
echo ""
echo "=========================================="
echo "Then add to Vercel:"
echo "=========================================="
echo ""
echo "1. Go to your Vercel project"
echo "2. Settings → Environment Variables"
echo "3. Add: MONGODB_URI = <your_connection_string>"
echo "4. Redeploy your project"
echo ""
echo "For detailed instructions, see: MONGODB_SETUP.md"
